# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eva van Rooijen
title: MSc Econometrics and Management Science - looking for thesis topic!
email: evav.rooijen@live.nl
# website: https://evavanrooijen.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: evalikesdata
github_username:  evavanrooijen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: evavrooijen
linkedin_username: evavanrooijen
# xing_username: jekyll
# pinterest_username: evavanrooijen
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Hello, World! #About Me
about_profile_image: images/plitvice-modified.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Eva and like to puzzle with data. 
  
  As well as working on predictive models I also have experience making visualisations and teaching. Through extracurricular activities, I have gained teamwork and leadership skills.

  I am most skilled in: <mark>Statistics</mark> and <mark>Python</mark>

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 
        caption: 2022 - 2023
        sub_title: MSc Econometrics and Management Science
        quote: >
          Erasmus University Rotterdam
        description: | # this will include new lines to allow paragraphs
           Analytics and Operations Research In Logistics
      - layout: left
        title: MSc Science Education and Communication
        caption: 2021 - 2023
        sub_title: TU Delft
        quote: >
          Communication Design for Innovation
        description: | # this will include new lines to allow paragraphs
                 Electives: Environmental Economics, Impact Evaluation
                 Causal Networks, Graph Theory, Climate Data Analysis, Evolutionary Algorithms

      - layout: left
        title: Erasmus University Rotterdam
        caption: 2016 - 2020
        sub_title: BSc2 Econometrics and Operations Research + BSc International Economics and Business Economics
        quote: >
          Thesis: Topic Modeling of News Articles - Model Validation by Topic Stability
        description: | # this will include new lines to allow paragraphs
            Minor: Advanced Computer Science, 8.7/10
            Major: Policy Economics, 8.2/10 
           
            
            National Research University HSE Moscow, Exchange Semester, Computer Science, 8.5/10
            Courses: Medical Informatics; Cognitive Neuroscience; Data Engineering; Machine Learning 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Art to Explain Neural Nets
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          internship at Science Centre TU Delft
        description: | # this will include new lines to allow paragraphs
          <img src="https://cdn-blog.adafruit.com/uploads/2016/04/1.jpg" style="padding-right: 50px;  float:left" alt="drawing" width="400" />
          Explored the use of art as science communication tool.
          
          - Designed an installation to help explain Neural Networks 
          - Collaborated with artists, mechanics and mathematicians.
          - Learnt how to work with arduino and join forces with my python code.
          - Additionally, made prototypes with various materials.

  - title: Experience 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Educator
        link: wisdombeyonddata.github.io
        link_text: wisdombeyonddata.com
        sub_title: Freelance
        caption: 2020- Present
        quote: >
          My purpose is to learn about my field, myself and others every day.
          My values are simplicity and wisdom.
        description: | # this will include new lines to allow paragraphs
            teach courses on python, data science and visualisations
               
      - layout: left
        title: Ministry of Internal Affairs
        sub_title: Data Scientist
        caption: 1/2021 - 9/2021
        quote: >
          Improving the search engine for open publication of officIal governmental documents
        description: | # this will include new lines to allow paragraphs
            After freelancing, was looking for teamwork and development.
                

       # title: Research Assistant

            

  - title: Extracurricular Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Chief AI Engineer
        caption: 2021 - 2022
        sub_title: TU Delft Dreamteam Epoch
        quote: 
        description: | # this will include new lines to allow paragraphs
                  
      - layout: top-middle
        title:  Honours Research Class
        caption: 2019-2020
        sub_title: Erasmus Honours Academy
        quote: >
        description: | # this will include new lines to allow paragraphs
              
      - layout: top-middle
        title: Personal Leadership Programme
        caption: 2019 - 2020
        sub_title: Erasmus Honours Academy
        quote: >
        description: | # this will include new lines to allow paragraphs
          

      - layout: top-middle
        title: Excellence Programme - AI
        caption: 2019 - 2020
        sub_title: FAECTOR Study Association
        quote: >
        description: | # this will include new lines to allow paragraphs
                    

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides this, I enjoy to:
      - design and sew clothes
      - travel on my motorcycle
      - view impressionism painting
 
      <img src="images/motor france.jpg" width="300"/>
      <img src="images/plitvice.jpg"  width="400"/>
      <img src="images/map.jpg"  alt="map" width="400" />
      <img src="images/giverny.jpg"  width="400"/>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
