# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eva van Rooijen
title: MSc Econometrics and Management Science - looking for thesis topic!
email: evav.rooijen@live.nl
website: https://evavanrooijen.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: evalikesdata
github_username:  evavanrooijen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: evavrooijen
linkedin_username: evavanrooijen
# xing_username: jekyll
# pinterest_username: evavanrooijen
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Hello, World! #About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Eva and like to puzzle with data. 
  
  As well as working on predictive models I also have experience making visualisations and teaching. Through extracurricular activities, I have gained teamwork and leadership skills.

  I am most skilled in: <mark>Statistics</mark> and <mark>Python</mark>

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
        title: Erasmus University Rotterdam
        caption: 2022 - 2023
        sub_title: MSc Econometrics and Management Science
        quote: >
          Analytics and Operations Research In Logistics
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: TU Delft
        caption: 2021 - 2023
        sub_title: MSc Science Education and Communication
        quote: >
          Communication Design for Innovation
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: left
        title: Erasmus University Rotterdam
        caption: 2016 - 2020
        sub_title: BSc Econometrics and Operations Research
        quote: >
          Thesis: Topic Modeling of News Articles - Model Validation by Topic Stability
        description: | # this will include new lines to allow paragraphs
            Minor: Advanced Computer Science, 8.7/10
              National Research University HSE Moscow, Exchange Semester, Computer Science, 8.5/10
            Courses: Medical Informatics; Cognitive Neuroscience; Data Engineering; Machine Learning 
      - layout: left
        title: Erasmus University Rotterdam
        caption: 2016 - 2020
        sub_title: BSc International Economics and Business Economics
        quote: >
          Thesis: Topic Modeling of News Articles - Model Validation by Topic Stability
        description: | # this will include new lines to allow paragraphs
          Major: Policy Economics, 8.2/10 Electives: Environmental Economics, Impact Evaluation

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides this, I enjoy to:
      - design and sew clothes
      - travel on my motorcycle
      - view impressionism painting
 
      ![Gardens of Monet]/images/giverny.jpg "Gardens of Monet")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
